### ISSUE TITLE
Some buttons have weird black background after exiting minigame

### ISSUE THREAD

**Issue by Cherry-Chip** [undefined06855/Icon-Ninja#4]
![image](https://github.com/user-attachments/assets/58a10691-a0b7-4747-a843-3094b92ff659)

Heya! I have something else that I'd like to report here.

After exiting the minigame, some buttons have a black sqaure appear behind them now. Going into another menu and exiting fixes the issue, but I am still assuming that this is unintended behavior.

- CherryChip.

**Comment by undefined06855** [comment]
this is an issue with pages API and cocos's FadeIn, I'll have a look

**Comment by undefined06855** [comment]
i think this got fixed like a week ago, going to close it now
