### ISSUE TITLE
Some smaller QOL suggestions that could enhance the mod!

### ISSUE THREAD

**Issue by Cherry-Chip** [undefined06855/Icon-Ninja#5]
Hi! Sorry for all the issues but I had a few suggestions. This would probably fall under the "Enhancement" label on GitHub.

I have suggestions for three simpler things that could be added to the mod's config.
1). **SFX VOLUME SLIDER:** A volume slider for the sound effects that play when entering/exiting the minigame.
2). **TEXT FONT CUSTOMIZATION:** Customizing the "Combo" text's font to one of the 60 in-game fonts.
3). **TRANSITION ANIMATION SPEED:** Adjust the speed of the transition that plays when entering/exiting the minigame.

I hope you find these ideas somewhat interesting! Have a blessed day.

- CherryChip

**Comment by undefined06855** [comment]
ill definitely have a look about 1 and 2, but unlikely 3

**Comment by Cherry-Chip** [comment]
awesome, ty! :D

**Comment by undefined06855** [comment]
1 and 2 have been added in v1.0.4
