### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by Tropical2X** [undefined06855/Icon-Ninja#7]
There's a bug (for mobile/touchscreen devices) where if you hold two fingers on the screen it won't just stay on one finger, but create a long in between them

https://github.com/user-attachments/assets/8923171a-3dbd-46cb-ae5d-4b0b284680f3

**Comment by undefined06855** [comment]
oh god 😭

**Comment by undefined06855** [comment]
fixed in v1.0.4, will release later today
